from fastapi import APIRouter, Depends, HTTPException
from datetime import datetime
from .auth import connect_to_db
from app.utils.jwt_util import get_current_user
from app.utils.report_logic import build_income_expense_report
from app.models.reports_models import ReportRequest

router = APIRouter(prefix="/api/v1/reports", tags=["Reports"])

# generate report request
@router.post("/generate")
def generate_report(
    payload: ReportRequest,
    curr_user: dict = Depends(get_current_user),
    conn = Depends(connect_to_db)
):
    # report title mapping 
    if payload.reportType == "income_expense":
        title = "Income vs Expense Report"
    elif payload.reportType == "tax_summary":
        title = "Tax Summary"
    elif payload.reportType == "cashflow":
        title = "Cashflow"
    else:
        raise HTTPException(status_code=400, detail="Unsupported report type")

    try:
        with conn.cursor() as cursor:

            # get first & last transaction dates 
            cursor.execute(
                """
                SELECT 
                    MIN("date") AS first_trx,
                    MAX("date") AS last_trx
                FROM transactions
                WHERE "userID" = %s;
                """,
                (curr_user["userID"],)
            )

            result = cursor.fetchone()

            if not result["first_trx"] or not result["last_trx"]:
                raise HTTPException(
                    status_code=400,
                    detail="No transactions found for this user"
                )

            first_trx_date = result["first_trx"].date()
            last_trx_date = result["last_trx"].date()

            # date validation 
            if payload.startDate < first_trx_date:
                payload.startDate = first_trx_date

            if payload.endDate > last_trx_date:
                payload.endDate = last_trx_date

            # insert report 
            generated_on = datetime.utcnow().date()

            cursor.execute(
                """
                INSERT INTO reports (title, report_type, generated_on, "from", "to", "userID")
                VALUES (%s, %s, %s, %s, %s, %s)
                RETURNING report_id;
                """,
                (
                    title,
                    payload.reportType,
                    generated_on,
                    payload.startDate,
                    payload.endDate,
                    curr_user["userID"]
                )
            )

            report_id = cursor.fetchone()["report_id"]
            conn.commit()

        return {
            "success": True,
            "report": {
                "id": str(report_id),
                "title": title,
                "generatedDate": datetime.utcnow().isoformat() + "Z",
                "type": payload.reportType,
                "dateRange": f"{payload.startDate} to {payload.endDate}"
            }
        }

    except HTTPException:
        conn.rollback()
        raise

    except Exception as e:
        conn.rollback()
        raise HTTPException(status_code=500, detail=str(e))


# fetch list of reports generated by a user
@router.get('/')
def get_my_reports(curr_user: dict = Depends(get_current_user), conn=Depends(connect_to_db)):
    with conn.cursor() as cursor:
        cursor.execute("""
        SELECT *
        FROM reports
        WHERE "userID"=%s;
""", (curr_user['userID'],))
        
        rows = cursor.fetchall()

    # if no report has been generated by user
    if not rows:
        return{
           "success": False
        }

    reports = []
    for r in rows:
        reports.append({
            "id": str(r["report_id"]),
            "title": r["title"],
            "type": r["report_type"],
            "generatedDate": r["generated_on"].isoformat(),
            "dateRange": f'{r["from"]} to {r["to"]}'
        })

    return {
        "success": True,
        "reports": reports
    }        



@router.get("/{report_id}")
def get_report_details(
    report_id: str,
    curr_user: dict = Depends(get_current_user),
    conn=Depends(connect_to_db)
):
    with conn.cursor() as cursor:

        #  Fetch report metadata
        cursor.execute(
            """
            SELECT report_id, title, report_type, generated_on, "from", "to"
            FROM reports
            WHERE report_id = %s AND "userID" = %s;
            """,
            (report_id, curr_user["userID"])
        )

        report = cursor.fetchone()
        if not report:
            raise HTTPException(status_code=404, detail="Report not found")

        # Dispatch based on report type
        if report["report_type"] == "income_expense":
            return build_income_expense_report(report, curr_user["userID"], cursor)

        #  Future reports
        # elif report["report_type"] == "tax_summary":
        #     return build_tax_summary_report(...)

        else:
            raise HTTPException(status_code=400, detail="Unsupported report type")
