"""Add transaction_rules table

Revision ID: 2d33f53e9327
Revises: 90ebcdfeb7cc
Create Date: 2026-04-19 20:10:44.554037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""Add transaction_rules table

Revision ID: 2d33f53e9327
Revises: 90ebcdfeb7cc
Create Date: 2026-04-19 20:10:44.554037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d33f53e9327'
down_revision: Union[str, Sequence[str], None] = '90ebcdfeb7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_rules',
    sa.Column('ruleID', sa.Integer(), nullable=False),
    sa.Column('categID', sa.Integer(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tx_type', sa.String(), nullable=True),
    sa.Column('exclude', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['categID'], ['categories.categID'], ),
    sa.PrimaryKeyConstraint('ruleID')
    )
    op.create_index(op.f('ix_transaction_rules_ruleID'), 'transaction_rules', ['ruleID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_rules_ruleID'), table_name='transaction_rules')
    op.drop_table('transaction_rules')
    # ### end Alembic commands ###
