"""create all tables

Revision ID: 90ebcdfeb7cc
Revises: 
Create Date: 2025-10-25 00:30:42.760422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ebcdfeb7cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('bankID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bankID')
    )
    op.create_table('categories',
    sa.Column('categID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('categID')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('userType', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('LOWER("userType") IN (\'freelancer\', \'businessman\')', name='check_user_type'),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_userID'), 'users', ['userID'], unique=False)
    op.create_table('accounts',
    sa.Column('accID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('bankID', sa.Integer(), nullable=True),
    sa.Column('accountTitle', sa.String(), nullable=False),
    sa.Column('accountNo', sa.String(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bankID'], ['banks.bankID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('accID')
    )
    op.create_table('transactions',
    sa.Column('trxID', sa.Integer(), nullable=False),
    sa.Column('trxNo', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trxDetail', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('trxType', sa.String(), nullable=False),
    sa.Column('isTaxable', sa.Boolean(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('accID', sa.Integer(), nullable=False),
    sa.Column('categID', sa.Integer(), nullable=False),
    sa.CheckConstraint('LOWER("trxType") IN (\'debit\', \'credit\')', name='check_trx_type'),
    sa.ForeignKeyConstraint(['accID'], ['accounts.accID'], ),
    sa.ForeignKeyConstraint(['categID'], ['categories.categID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('trxID')
    )
    op.create_index(op.f('ix_transactions_trxID'), 'transactions', ['trxID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_trxID'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_userID'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    op.drop_table('banks')
    # ### end Alembic commands ###
