"""Add categorized_by column and make categID nullable

Revision ID: b4925a8b1d6c
Revises: 2d33f53e9327
Create Date: 2026-04-19 20:39:23.098553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""Add categorized_by column and make categID nullable

Revision ID: b4925a8b1d6c
Revises: 2d33f53e9327
Create Date: 2026-04-19 20:39:23.098553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4925a8b1d6c'
down_revision: Union[str, Sequence[str], None] = '2d33f53e9327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('categorized_by', sa.String(), nullable=True))
    op.alter_column('transactions', 'categID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'categID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'categorized_by')
    # ### end Alembic commands ###
